### ISSUE TITLE
The package 'react-native-volume-manager' doesn't seem to be linked

### ISSUE THREAD

**Issue by leminhcse** [hirbod/react-native-volume-manager#20] opened 2023-09-08 07:09 UTC
Hi team, 

My android app is using with following configuration: 
- react-native: "0.69.5"
- react-native-volume-manager: "^1.10.0"
- org.jetbrains.kotlin:kotlin-gradle-plugin: "1.6.0"

but when run on android, the error show: 

<img width="248" alt="Screenshot 2023-09-08 at 09 12 35" src="https://github.com/hirbod/react-native-volume-manager/assets/45330126/286bd582-a079-4393-b77e-6c2afd711c93">

However, it works normally on iOS. How to resolve it ? Although, I tried to down-grade react-native-volume-manager to below version but didn't still work.

**Comment by hirbod** [comment] 2023-09-11 08:23
Not sure what happened in your case, maybe its related to RN 0.69.5 - I do not support old versions. I think you need to upgrade to 0.71+

**Comment by ntphuongHD** [comment] 2023-09-11 08:38
I got same the issue, have you any solution without upgrade to 0.71+ ?

**Comment by ntphuongHD** [comment] 2023-09-11 08:39
> I got same the issue, have you any solution without upgrade to 0.71+ ?

I got same the issue, have you any solution without upgrade to 0.71+ ?

**Comment by ntphuongHD** [comment] 2023-09-11 08:39
> Not sure what happened in your case, maybe its related to RN 0.69.5 - I do not support old versions. I think you need to upgrade to 0.71+

I got same the issue, have you any solution without upgrade to 0.71+ ?

**Comment by canven** [comment] 2023-09-14 08:45
same problem occurs in  react native version  0.72.0 

I meet the errors when compile it , 

```
[!] CDN: trunk Repo update failed - 10 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/0/c/Mute/0.1.0/Mute.podspec.json Response: Timeout was reached 
```

but I attach url <https://cdn.jsdelivr.net/cocoa/Specs/0/0/c/Mute/0.1.0/Mute.podspec.json > to brower.  Url can explore it , 
I confused about it .
![图片](https://github.com/hirbod/react-native-volume-manager/assets/12689433/c6272d19-2fec-4368-80b4-86b9e1cb21db)

**Comment by hirbod** [comment] 2023-09-14 13:13
@canven that issue is unrelated and there was a Response timeout. Either a network issue or the CDN was down at the time.

**Comment by canven** [comment] 2023-09-18 10:01
> @canven that issue is unrelated and there was a Response timeout. Either a network issue or the CDN was down at the time.

 I try to install package again ,  it has ran like a charm. It may network problem for me in my side,  Thanks for your efforts.  Best Regards .

**Comment by hirbod** [comment] 2023-09-18 13:29
I am closing this issue, since I can't reproduce any issues in recent React Native versions and I can't maintain older versions unfortunately.

**Closed as completed by hirbod** 2023-09-18 13:29 UTC

**Comment by yanoyuki** [comment] 2024-10-19 07:18
I am also encountering the same issue on the iOS simulator.

In my `package.json`, I am using the following versions:

```
"react-native": "0.74.5",
"react-native-volume-manager": "^1.10.0",
```

It reproduces on iOS 15.5 (iPhone SE 1st Generation), which is a slightly older OS.

For reference, it works fine and does not reproduce on iOS 17, 18, or Android.

**Comment by justsomeofl** [comment] 2026-01-25 06:22
Same issue with:
> 
"react-native": "0.83.1", 
"react-native-volume-manager": "2.0.8"
>
